name: physiscoletor
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
 # sdk: '>=3.1.2 <4.0.0'
  #sdk: '>=2.0.0-dev.58.0 <3.0.0'
  sdk: ">=2.17.0-69.2.beta <3.1.3"

dependencies: 
  flutter:
    sdk: flutter
  
  flutter_bluetooth_serial:  # Adicione esta dependência para trabalhar com Bluetooth
 # barcode_scan2: # Adicione esta dependência para ler códigos de barras   
  http:      
  image:
  esc_pos_utils:  
  #flutter_barcode_scanner:
  #bluetooth_thermal_printer:
  blue_thermal_printer:
  flutter_blue:  
  bluetooth_thermal_printer:
  barcode_scan2:

dev_dependencies:
  flutter_test:
    sdk: flutter
 # flutter_lints: ^2.0.0 

flutter:
  uses-material-design: true


